name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    uses: ./.github/workflows/build_linux.yml
    with:
      version: ${{ github.ref_name }}

  macos:
    uses: ./.github/workflows/build_macos.yml
    with:
      version: ${{ github.ref_name }}

  windows:
    uses: ./.github/workflows/build_windows.yml
    with:
      version: ${{ github.ref_name }}

  release:
    needs: [linux, macos, windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4

      - name: Rename artifacts
        run: |
          mv odx-linux-amd64/odx odx-linux-amd64/odx-linux-amd64
          mv odx-macos-amd64/odx odx-macos-amd64/odx-macos-amd64
          mv odx-windows-amd64.exe/odx.exe odx-windows-amd64.exe/odx-windows-amd64.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            odx-linux-amd64/odx-linux-amd64
            odx-macos-amd64/odx-macos-amd64
            odx-windows-amd64.exe/odx-windows-amd64.exe